//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.07 at 03:02:30 PM CEST 
//


package com.christian.icecat.model.product;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.christian.icecat.model.product package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.christian.icecat.model.product
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Files }
     * 
     */
    public Files createFiles() {
        return new Files();
    }

    /**
     * Create an instance of {@link FeatureValuesVocabularyList }
     * 
     */
    public FeatureValuesVocabularyList createFeatureValuesVocabularyList() {
        return new FeatureValuesVocabularyList();
    }

    /**
     * Create an instance of {@link ProductsComplaintResponse }
     * 
     */
    public ProductsComplaintResponse createProductsComplaintResponse() {
        return new ProductsComplaintResponse();
    }

    /**
     * Create an instance of {@link StatisticQueryDateDataReportResponse }
     * 
     */
    public StatisticQueryDateDataReportResponse createStatisticQueryDateDataReportResponse() {
        return new StatisticQueryDateDataReportResponse();
    }

    /**
     * Create an instance of {@link ProductGallery }
     * 
     */
    public ProductGallery createProductGallery() {
        return new ProductGallery();
    }

    /**
     * Create an instance of {@link DescribeProductsResponse }
     * 
     */
    public DescribeProductsResponse createDescribeProductsResponse() {
        return new DescribeProductsResponse();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link ProductMultimediaObject }
     * 
     */
    public ProductMultimediaObject createProductMultimediaObject() {
        return new ProductMultimediaObject();
    }

    /**
     * Create an instance of {@link Countries }
     * 
     */
    public Countries createCountries() {
        return new Countries();
    }

    /**
     * Create an instance of {@link DistributorList }
     * 
     */
    public DistributorList createDistributorList() {
        return new DistributorList();
    }

    /**
     * Create an instance of {@link Files.File }
     * 
     */
    public Files.File createFilesFile() {
        return new Files.File();
    }

    /**
     * Create an instance of {@link ICECATInterface }
     * 
     */
    public ICECATInterface createICECATInterface() {
        return new ICECATInterface();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link FeatureLogoValue }
     * 
     */
    public FeatureLogoValue createFeatureLogoValue() {
        return new FeatureLogoValue();
    }

    /**
     * Create an instance of {@link ProductBulletGroup }
     * 
     */
    public ProductBulletGroup createProductBulletGroup() {
        return new ProductBulletGroup();
    }

    /**
     * Create an instance of {@link VirtualCategory }
     * 
     */
    public VirtualCategory createVirtualCategory() {
        return new VirtualCategory();
    }

    /**
     * Create an instance of {@link LanguageList }
     * 
     */
    public LanguageList createLanguageList() {
        return new LanguageList();
    }

    /**
     * Create an instance of {@link StatisticQuery }
     * 
     */
    public StatisticQuery createStatisticQuery() {
        return new StatisticQuery();
    }

    /**
     * Create an instance of {@link StatisticQueryDate }
     * 
     */
    public StatisticQueryDate createStatisticQueryDate() {
        return new StatisticQueryDate();
    }

    /**
     * Create an instance of {@link ReasonsToBuy }
     * 
     */
    public ReasonsToBuy createReasonsToBuy() {
        return new ReasonsToBuy();
    }

    /**
     * Create an instance of {@link Measure }
     * 
     */
    public Measure createMeasure() {
        return new Measure();
    }

    /**
     * Create an instance of {@link Descriptions }
     * 
     */
    public Descriptions createDescriptions() {
        return new Descriptions();
    }

    /**
     * Create an instance of {@link EANCode }
     * 
     */
    public EANCode createEANCode() {
        return new EANCode();
    }

    /**
     * Create an instance of {@link Feature }
     * 
     */
    public Feature createFeature() {
        return new Feature();
    }

    /**
     * Create an instance of {@link FeaturesList }
     * 
     */
    public FeaturesList createFeaturesList() {
        return new FeaturesList();
    }

    /**
     * Create an instance of {@link ProductsList }
     * 
     */
    public ProductsList createProductsList() {
        return new ProductsList();
    }

    /**
     * Create an instance of {@link ProductFeature }
     * 
     */
    public ProductFeature createProductFeature() {
        return new ProductFeature();
    }

    /**
     * Create an instance of {@link RestrictedValue }
     * 
     */
    public RestrictedValue createRestrictedValue() {
        return new RestrictedValue();
    }

    /**
     * Create an instance of {@link ProductBulletsHTML }
     * 
     */
    public ProductBulletsHTML createProductBulletsHTML() {
        return new ProductBulletsHTML();
    }

    /**
     * Create an instance of {@link SummaryDescriptionAttr }
     * 
     */
    public SummaryDescriptionAttr createSummaryDescriptionAttr() {
        return new SummaryDescriptionAttr();
    }

    /**
     * Create an instance of {@link SummaryDescription }
     * 
     */
    public SummaryDescription createSummaryDescription() {
        return new SummaryDescription();
    }

    /**
     * Create an instance of {@link ProductDescription }
     * 
     */
    public ProductDescription createProductDescription() {
        return new ProductDescription();
    }

    /**
     * Create an instance of {@link ParentCategory }
     * 
     */
    public ParentCategory createParentCategory() {
        return new ParentCategory();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     */
    public Keywords createKeywords() {
        return new Keywords();
    }

    /**
     * Create an instance of {@link ProductsListLookup }
     * 
     */
    public ProductsListLookup createProductsListLookup() {
        return new ProductsListLookup();
    }

    /**
     * Create an instance of {@link ParentProductFamily }
     * 
     */
    public ParentProductFamily createParentProductFamily() {
        return new ParentProductFamily();
    }

    /**
     * Create an instance of {@link Names }
     * 
     */
    public Names createNames() {
        return new Names();
    }

    /**
     * Create an instance of {@link FeatureGroup }
     * 
     */
    public FeatureGroup createFeatureGroup() {
        return new FeatureGroup();
    }

    /**
     * Create an instance of {@link ProductFamily }
     * 
     */
    public ProductFamily createProductFamily() {
        return new ProductFamily();
    }

    /**
     * Create an instance of {@link Sign }
     * 
     */
    public Sign createSign() {
        return new Sign();
    }

    /**
     * Create an instance of {@link Series }
     * 
     */
    public Series createSeries() {
        return new Series();
    }

    /**
     * Create an instance of {@link SupplierCategoriesList }
     * 
     */
    public SupplierCategoriesList createSupplierCategoriesList() {
        return new SupplierCategoriesList();
    }

    /**
     * Create an instance of {@link SupplierProductFamiliesList }
     * 
     */
    public SupplierProductFamiliesList createSupplierProductFamiliesList() {
        return new SupplierProductFamiliesList();
    }

    /**
     * Create an instance of {@link CategoryFeaturesList }
     * 
     */
    public CategoryFeaturesList createCategoryFeaturesList() {
        return new CategoryFeaturesList();
    }

    /**
     * Create an instance of {@link ProductsStatistic }
     * 
     */
    public ProductsStatistic createProductsStatistic() {
        return new ProductsStatistic();
    }

    /**
     * Create an instance of {@link FeatureLogoCategory }
     * 
     */
    public FeatureLogoCategory createFeatureLogoCategory() {
        return new FeatureLogoCategory();
    }

    /**
     * Create an instance of {@link ProductAffiliated }
     * 
     */
    public ProductAffiliated createProductAffiliated() {
        return new ProductAffiliated();
    }

    /**
     * Create an instance of {@link StatisticQueryDatesListResponse }
     * 
     */
    public StatisticQueryDatesListResponse createStatisticQueryDatesListResponse() {
        return new StatisticQueryDatesListResponse();
    }

    /**
     * Create an instance of {@link SuppliersList }
     * 
     */
    public SuppliersList createSuppliersList() {
        return new SuppliersList();
    }

    /**
     * Create an instance of {@link ProductBulletsHTMLs }
     * 
     */
    public ProductBulletsHTMLs createProductBulletsHTMLs() {
        return new ProductBulletsHTMLs();
    }

    /**
     * Create an instance of {@link RestrictedValues }
     * 
     */
    public RestrictedValues createRestrictedValues() {
        return new RestrictedValues();
    }

    /**
     * Create an instance of {@link ProductBullets }
     * 
     */
    public ProductBullets createProductBullets() {
        return new ProductBullets();
    }

    /**
     * Create an instance of {@link CategoriesList }
     * 
     */
    public CategoriesList createCategoriesList() {
        return new CategoriesList();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link StatisticQueryListResponse }
     * 
     */
    public StatisticQueryListResponse createStatisticQueryListResponse() {
        return new StatisticQueryListResponse();
    }

    /**
     * Create an instance of {@link LocalValue }
     * 
     */
    public LocalValue createLocalValue() {
        return new LocalValue();
    }

    /**
     * Create an instance of {@link VirtualCategories }
     * 
     */
    public VirtualCategories createVirtualCategories() {
        return new VirtualCategories();
    }

    /**
     * Create an instance of {@link FulltextProductsSearchResponse }
     * 
     */
    public FulltextProductsSearchResponse createFulltextProductsSearchResponse() {
        return new FulltextProductsSearchResponse();
    }

    /**
     * Create an instance of {@link CategoryFeatureGroup }
     * 
     */
    public CategoryFeatureGroup createCategoryFeatureGroup() {
        return new CategoryFeatureGroup();
    }

    /**
     * Create an instance of {@link FeatureValue }
     * 
     */
    public FeatureValue createFeatureValue() {
        return new FeatureValue();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Supplier }
     * 
     */
    public Supplier createSupplier() {
        return new Supplier();
    }

    /**
     * Create an instance of {@link ProductRelated }
     * 
     */
    public ProductRelated createProductRelated() {
        return new ProductRelated();
    }

    /**
     * Create an instance of {@link MeasuresList }
     * 
     */
    public MeasuresList createMeasuresList() {
        return new MeasuresList();
    }

    /**
     * Create an instance of {@link FeatureGroupsList }
     * 
     */
    public FeatureGroupsList createFeatureGroupsList() {
        return new FeatureGroupsList();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link ProductBullet }
     * 
     */
    public ProductBullet createProductBullet() {
        return new ProductBullet();
    }

    /**
     * Create an instance of {@link ProductBundled }
     * 
     */
    public ProductBundled createProductBundled() {
        return new ProductBundled();
    }

    /**
     * Create an instance of {@link FeatureLogo }
     * 
     */
    public FeatureLogo createFeatureLogo() {
        return new FeatureLogo();
    }

    /**
     * Create an instance of {@link FeatureValuesList }
     * 
     */
    public FeatureValuesList createFeatureValuesList() {
        return new FeatureValuesList();
    }

    /**
     * Create an instance of {@link FeatureLogoCategoriesList }
     * 
     */
    public FeatureLogoCategoriesList createFeatureLogoCategoriesList() {
        return new FeatureLogoCategoriesList();
    }

    /**
     * Create an instance of {@link Signs }
     * 
     */
    public Signs createSigns() {
        return new Signs();
    }

    /**
     * Create an instance of {@link FeatureValuesVocabularyList.FeatureValuesVocabulary }
     * 
     */
    public FeatureValuesVocabularyList.FeatureValuesVocabulary createFeatureValuesVocabularyListFeatureValuesVocabulary() {
        return new FeatureValuesVocabularyList.FeatureValuesVocabulary();
    }

    /**
     * Create an instance of {@link ProductsComplaintResponse.ProductComplaintReponse }
     * 
     */
    public ProductsComplaintResponse.ProductComplaintReponse createProductsComplaintResponseProductComplaintReponse() {
        return new ProductsComplaintResponse.ProductComplaintReponse();
    }

    /**
     * Create an instance of {@link StatisticQueryDateDataReportResponse.StatisticQueryDateDataReport }
     * 
     */
    public StatisticQueryDateDataReportResponse.StatisticQueryDateDataReport createStatisticQueryDateDataReportResponseStatisticQueryDateDataReport() {
        return new StatisticQueryDateDataReportResponse.StatisticQueryDateDataReport();
    }

    /**
     * Create an instance of {@link ProductGallery.ProductPicture }
     * 
     */
    public ProductGallery.ProductPicture createProductGalleryProductPicture() {
        return new ProductGallery.ProductPicture();
    }

    /**
     * Create an instance of {@link DescribeProductsResponse.DescribeProductResponse }
     * 
     */
    public DescribeProductsResponse.DescribeProductResponse createDescribeProductsResponseDescribeProductResponse() {
        return new DescribeProductsResponse.DescribeProductResponse();
    }

    /**
     * Create an instance of {@link Body.Line }
     * 
     */
    public Body.Line createBodyLine() {
        return new Body.Line();
    }

    /**
     * Create an instance of {@link ProductMultimediaObject.MultimediaObject }
     * 
     */
    public ProductMultimediaObject.MultimediaObject createProductMultimediaObjectMultimediaObject() {
        return new ProductMultimediaObject.MultimediaObject();
    }

    /**
     * Create an instance of {@link Countries.Country }
     * 
     */
    public Countries.Country createCountriesCountry() {
        return new Countries.Country();
    }

    /**
     * Create an instance of {@link DistributorList.Distributor }
     * 
     */
    public DistributorList.Distributor createDistributorListDistributor() {
        return new DistributorList.Distributor();
    }

}
